/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BaseLayout: typeof import('./components/BaseLayout.vue')['default']
    Button: typeof import('primevue/button')['default']
    ColorMode: typeof import('./components/ColorMode.vue')['default']
    ColorModeToggle: typeof import('./components/ColorModeToggle.vue')['default']
    DesktopNav: typeof import('./components/DesktopNav.vue')['default']
    DesktopNavigationBar: typeof import('./components/DesktopNavigationBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MobileNav: typeof import('./components/MobileNav.vue')['default']
    MobileNavigationBar: typeof import('./components/MobileNavigationBar.vue')['default']
    NavBarUserSection: typeof import('./components/NavBarUserSection.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    PrimeVueExample: typeof import('./components/PrimeVueExample.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
