/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BaseLayout: typeof import('./components/BaseLayout.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Chip: typeof import('primevue/chip')['default']
    ColorMode: typeof import('./components/ColorMode.vue')['default']
    ColorModeToggle: typeof import('./components/ColorModeToggle.vue')['default']
    ContentGrid: typeof import('./components/ContentGrid.vue')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    DataView: typeof import('primevue/dataview')['default']
    DesktopNav: typeof import('./components/DesktopNav.vue')['default']
    DesktopNavigationBar: typeof import('./components/DesktopNavigationBar.vue')['default']
    GoogleMap: typeof import('./components/GoogleMap.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./components/ContentGrid.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MobileNav: typeof import('./components/MobileNav.vue')['default']
    MobileNavigationBar: typeof import('./components/MobileNavigationBar.vue')['default']
    NavBarUserSection: typeof import('./components/NavBarUserSection.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    PrimeVueExample: typeof import('./components/PrimeVueExample.vue')['default']
    Procard: typeof import('./components/Procard.vue')['default']
    ProductActions: typeof import('./components/ProductActions.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    ProductChips: typeof import('./components/ProductChips.vue')['default']
    ProductImage: typeof import('./components/ProductImage.vue')['default']
    ProductInfo: typeof import('./components/ProductInfo.vue')['default']
    ProductStatusTag: typeof import('./components/ProductStatusTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    SectionHeader: typeof import('./components/SectionHeader.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    TestProduct: typeof import('./components/TestProduct.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
